### ISSUE TITLE
Doubt about version

### ISSUE THREAD

**Issue by astratto** [NeoSmartpen/Documentations#1]
Hi, I started playing with my notes following your documentation (thanks for releasing it!), but I noticed that even though the file `NeoNote_data_Eng_20160117.pdf` says that the last version of the notes is 2, mine have a field set to 3.

```
$ hexdump Work/Data/0001.page_store/page.data
0000000 6e 65 6f 03 ...
```

I guess there's another version of this document that needs to be uploaded?

**Comment by Jenhay** [comment]
Stefano, you're right. there are some missing info for page version 3
I will update it this week.

**Comment by astratto** [comment]
@Jenhay Thanks, I've just noticed a new version has been uploaded.
Even though it still says version 2 is the latest version, the actual structure has changed and I guess it reflects the new format.

What do you think about converting that PDF to Markdown, so that it's easier to edit it?

Thanks

**Comment by Jenhay** [comment]
I will upload it as a markup language for the easy modification.

**Comment by astratto** [comment]
Brilliant! Thanks!
I think that's just a typo and the latest version is 3.
Following the new documentation I managed to parse correctly my notes.

It'd be nice to have more information about how some fields are to be interpreted, but I'll probably open another issue or comment on the file once it's in an editable format.

**Comment by astratto** [comment]
@Jenhay I think we can close this issue.

I've played a bit with the documentation and managed to parse the Google Docs format.
It's not really clear how to convert the coordinates to _drawable_ SVG lines, I guess I'll have to read the Android source code.

Do you have clearer docs for that?
