### ISSUE TITLE
Conversion NCode Unit to mm

### ISSUE THREAD

**Issue by josepaiva94** [NeoSmartpen/Documentations#10]
Hi,
In [Ncode™ Service Development Getting Started Guide v1.01.pdf](https://github.com/NeoSmartpen/Documentations/blob/master/Ncode%E2%84%A2%20Service%20Development%20Getting%20Started%20Guide%20v1.01.pdf), page 6, you mention 1 unit of NCode ≃ 2.37mm.

However, if I convert my captures using that scale, I get values like 303mm for a dot in the bottom of a 297mm page (`notebookId 609`). Any hints?

**Comment by chyccs** [comment]
The idea pad is a4 size, but it's actually printed on a larger piece of paper and cut into a4 size. Therefore, the upper left corner of a4 is not the coordinate 0,0.
The actual area of this note is left 5.48, top 16.02, width 88.58, and height 114.73 in ncode coordinates.
If you write at the bottom of the note, 16.02 + 114.73 will be the y-coordinate.

**Comment by josepaiva94** [comment]
Great, thank you! Where can I get this information for all paper sizes?

**Comment by chyccs** [comment]
It's hard to tell all the paper information. Tell me the note you want and I'll give you the information.
We are preparing a service to provide paper information in the future.

**Comment by josepaiva94** [comment]
Ok, I'll be anxiously waiting that service to come out. I don't have a specific note to ask as in my system users are free to upload captures in any note type.

**Comment by chyccs** [comment]
Hi, How are you.
I remember our previous conversation.
Now we can provide way to get our paper information.
If you want to use it, please tell me.
Thanks,

**Comment by josepaiva94** [comment]
Great! Please, tell me!

**Comment by chyccs** [comment]
can you tell me your email address?

**Comment by josepaiva94** [comment]
I've it on my profile, but here it is josepaiva94@gmail.com
