### ISSUE TITLE
PC용 SDK 제공 여부

### ISSUE THREAD

**Issue by Deokhyun-Yun** [NeoSmartpen/Documentations#2]
안녕하세요

저희는 일반 PC 용 솔루션에 전자펜을 적용하고자 합니다.
PC용 SDK를 받을 수 있습니까?
윈도우용 솔루션이며 주로 c++ 언어를 사용 중입니다.

**Comment by NeolabConvergence** [comment]
안녕하세요.

저희가 8~9월 정도에 윈도우즈용 SDK를 오픈할 계획을 갖고 있습니다.
지원 언어는 .NET (C#) 입니다.

감사합니다.
