### ISSUE TITLE
Ranges of x y coordinates

### ISSUE THREAD

**Issue by zpleal** [NeoSmartpen/Documentations#3]
The Neo Note Data File Format states in section 4.1 
  
 * x,y: 0 ~1, float
 * pressure: 0-1, float

I interpret this as meaning that x and y coordinates, as well as pressure, are floats with values ranging between 0 and 1.

In fact, pressure values are in the [0,1] range but not the x,y coordinates. The x coordinates seem to be in the [ 0, page_width] range and the y coordinates in the [0, page_height] range. Could you please confirm this and fix the documentation?

Thanks in advance

José Paulo Leal

**Comment by louisjrpark** [comment]
Dear Professor Leal,

In the Neo Note Data File format version 3, x, y coordinates were saved as a normalized form that they are divided by a max value of paper height and paper width and they were restored by multiplying a max value of paper height and paper width again.
In the current format version 4, x, y coordinates are not the normalized form, but, x, y coordinates of paper. Sorry for the confusion.

Thanks

Best regards,
Louis Park
