### ISSUE TITLE
What scaling factor is used by each device type? How to determine the device type?

### ISSUE THREAD

**Issue by zpleal** [NeoSmartpen/Documentations#4]
We are extracting x and y coordinates, as well as pressure, from notebooks. In our tests, we discovered that this process depends on the device (tablet, smartphone)  that was paired with the smartpen to produce the notebook ZIP archives. A workaround to this problem is to use a scale factor, that is actually easy to determine for each case. However,  we would like to automatically determine what scale should be applied in each case.

We noticed that  NoteInfo.xml file has general information on the notebook, and that it includes a <digitalNoteType> element that is not described in the documentation. In all the files we have seen so far, this element contains an integer. Could anyone please tell us what the meaning of this code? It doesn't seem to be the operating system (iOS, Android). Could it be the model? Also, if there is a relationship between the <digitalNoteType> and scales, could you please explain it? 

Thanks in advance

José Paulo Leal

**Comment by louisjrpark** [comment]
Dear Professor Leal,

Here are my answers to your following questions.

1. scale factor according to the device
We are converting X, Y coordinates from nCode paper into X, Y coordinates for device LCD to fit them within the area of the device LCD as follows.

X or Y coordinates = X or Y coordinates from nCode paper * page screen ratio 
(Page screen ratio : 
    float xRatio=view frame.size.width/paperSize.width
    float yRatio=view frame.size.height/paperSize.height
    float ratio = MIN(yRatio, xRatio)
    Page screen ratio = ratio )

You can refer to "IOSSDK2.0/iOSSDK2.0_sample_code/n2sample/NJPageCanvasController.m/(void)adjustCanvasView method" 
and "IOSSDK2.0/iOSSDK2.0_sample_code/n2sample/NJPageCanvasView.m/(void)touchBeganX 
 or touchMovedX method for more details.

2. <digitalNoteType> from NoteInfo.xml
DigitalNoteType is used for whether or not the cover image of a notebook uploaded to Google Drive is the image customized by a user. Thus, there is no relationship between DigitalNoteType and scales.

Thanks

Best regards,
Louis Park
