### ISSUE TITLE
Transcribe Library

### ISSUE THREAD

**Issue by DavidReidUK1985** [NeoSmartpen/Documentations#7]
Hi,

We are looking to integrate the NeoSmartpen into our application with a requirement on transcription. 

Please tell me which library you recommend for Transcription? We have tested Azure Cognitive services, but find that the Neo Notes iPhone Application gets much better results. 

Could you tell us what library you use within Neo Notes?

Thanks
David

**Comment by KyoungSu** [comment]
Hello David,

Thank you for your interest in NeoSmartpen.
Currently we are using MyScript solution.

Thank you,
Kyoungsu

**Comment by DavidReidUK1985** [comment]
Hi Kyoungsu,

Thank you very much.

Thanks
David
