### ISSUE TITLE
Is there any version of Bluttooth.LE document for NWP-F50?

### ISSUE THREAD

**Issue by takahiro-yonei** [NeoSmartpen/Documentations#9]
Hi,
Thank you for your great works!

I'm trying to integrate the NeoSmartpen(model: NWP-F50) with my application.
And I use [NeoLab_F1XX.Bluetooth.LE.pdf](https://github.com/NeoSmartpen/Documentations/blob/master/NeoLAB_F1XX.Bluetooth.LE.pdf) as a reference.

This document says that the NeoSmartpen has a service "Write Pen" and the "AssignedNumber" is "0x18F1".
But I could not find the service "Write Pen" in my NeoSmartpen(NWP-F50).

On the other hand, I scanned the NeoSmartpen with "LightBlue Explorer".
It seems there is one service assigned "0x19F1".

![LightBule_Explorer](https://user-images.githubusercontent.com/863990/57745663-01caf500-7709-11e9-8c22-b2588e937872.jpg)

How could I find the service "Write Pen", "Offline Data 1" (and so on) in the NeoSmartpen?
Is there another version of this document that is not uploaded yet?

Thank you in advance.

**Comment by takahiro-yonei** [comment]
@NeolabConvergence 
Hi,

Is there any update or any comment about this issue?
I really appreciate if you could comment to this issue.
Thank you in advance.

**Comment by NeolabConvergence** [comment]
I'm sorry to the answer late. Currently, the published document is Protocol 1.0 support document and is available only on the F110 model.  The pens other than the F110 are currently supported only through the Pen SDK 2.0.
Thank you.

**Comment by takahiro-yonei** [comment]
@NeolabConvergence 
Hi, 

Thank you for your reply.

> The pens other than the F110 are currently supported only through the Pen SDK 2.0.

I understood the above.

Thank you so much again.
